name: Create Release Zip

on:
  workflow_dispatch:
    inputs:
      build_path:
        description: 'Path to the directory to zip'
        required: true
        default: 'dist'

jobs:
  zip_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project (replace with your build steps)
        run: |
          mkdir -p dist
          echo "My project content" > dist/index.html
          echo "console.log('App started');" > dist/app.js

      - name: Create project zip archive
        uses: your-username/file-archiver-action@v1  # Replace with the actual repo/action name
        with:
          operation: zip
          archive_path: project-release.zip
          source_path: ${{ github.event.inputs.build_path }}
          commit_changes: true
          commit_message: "Action: Created project-release.zip"

      - name: List files in workspace
        run: ls -lh
